### ISSUE TITLE
Spam control?

### ISSUE THREAD

**Issue by ser** [KENET-KE/django-ldap-user-registration#1]
How do you manage spam control? reCaptcha would be useful, for example https://github.com/praekelt/django-recaptcha

**Comment by sureronald** [comment]
Spam control not yet built but I will add this in the next release. Thanks for the suggestion too.

**Comment by ser** [comment]
Do you want me to work on it? If yes, is the last code you have, submitted already to master branch?

**Comment by sureronald** [comment]
Yes you can work on it. I have just pushed the last piece of code I have had on my repo. I had started working on a small admin interface to manage the user requests and I hope to finish up on this in March when I will have some time for the project.
I don't have any rules for contribution but just a fork followed by a PR request will be good enough.

**Comment by ser** [comment]
Great, thanks - please expect a PR soon, as I desperately need to kick out spammers :)

**Comment by sureronald** [comment]
Fixed in #3
