### ISSUE TITLE
Improve installation steps

### ISSUE THREAD

**Issue by ghost** [KENET-KE/django-ldap-user-registration#5]
I walked through the installation guide. I'm unable to understand most of it. I would love to improve the installation guide, but I'm not sure where to start. I'll include some questions below for each step. If we get those answered I may be able to figure it out, then improve the guide.

Info: I started out by creating a separate python venv. Then starting two docker containers for phpLDAPadmin and openldap.

1. Add “dl_user” to your INSTALLED_APPS setting like this plus the other required dependencies:
? Where do I find dl_user? Is it a file? What dependencies are needed? Am I supposed to have a django server or something already setup?

2. In your Django root execute the command below to create your database tables:
? Am I supposed to have a database set up? When I run it now I get " No module named 'dj_database_url'"

Stopped at 3.

**Comment by sureronald** [comment]
Hi @tiedtoastar , What is your intended setup? You want to install as an app on an already existing django project or you want to set up a dev environment?
Thanks for your effort to help improve the guide!

**Comment by ghost** [comment]
@sureronald 2. set up a dev environment

**Comment by ghost** [comment]
My dev environment is now working. Most of my problems were due to inexperience with django.
Here are some notes. I will come back later with a pull reQuest for the improved documentation.

`Setup virtual environment

Install python-ldap dependencies
requires the module to be built so the dev box needs thhe following installed:
sudo apt-get install libsasl2-dev python3-dev libldap2-dev libssl-dev
then build: pip install python-ldap

install all other dependencies

in the folder django_ldap_user_registration
copy the local_settings.py.default
paste and rename to local_settings.py
change ldap settings:
LDAP_BASE_DN = 'ou=People,dc=example,dc=org'
LDAP_BIND_DN = 'cn=admin,dc=example,dc=org'

run a docker container locally

sudo docker run -p 389:389 --name my-openldap-container --detach osixia/openldap:1.2.4

test the running openldap
docker exec my-openldap-container ldapsearch -x -H ldap://localhost -b dc=example,dc=org -D "cn=admin,dc=example,dc=org" -w admin

install sqlite
sudo apt install sqlite3 --probably don't need this

comment out this line in settings.py: 
DATABASES['default'] = dj_database_url.config(default='postgres://...', conn_max_age=600)


python manage.py migrate
python manage.py runserver



`

**Comment by sureronald** [comment]
Great!
